name: Deploy React App and Backend to DigitalOcean (React Admin + Backend)

on:
  push:
    branches:
      - main  # Deploy only on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Add SSH private key to authenticate with DigitalOcean
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Verify SSH key is added correctly
      - name: Verify SSH key is added
        run: ssh-add -l

      # Debug: Test SSH connection with verbose logging
      - name: Test SSH connection with verbose logging
        run: |
          ssh -v -o StrictHostKeyChecking=no ${{ secrets.DIGITALOCEAN_USERNAME }}@${{ secrets.DIGITALOCEAN_HOST }} 'echo "SSH connection successful"'

      # Deploy React Admin (Frontend)
      - name: Deploy React Admin (Frontend)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/apps/nazimabad_portal/frontend # Adjust this to the correct path on your server
            git pull origin main
            npm i  # Clean install dependencies
            npm run build
            rm -rf /var/www/html/community/
            mkdir /var/www/html/community
            mv dist/* /var/www/html/community

      # Deploy Backend (NestJS)
      - name: Deploy Backend (NestJS)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/apps/nazimabad_portal/backend # Adjust this to the correct path on your server
            git pull origin main
            npm i  # Clean install dependencies
            npm run build

      # Restart Nginx
      - name: Restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart nginx

      # Restart PM2 for Backend
      - name: Restart PM2 process for Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pm2 restart 4  # Restarts the process with ID 4
